### ISSUE TITLE
`Uncaught TypeError: e.browser is undefined` error in WordPress 5.7.2

### ISSUE THREAD

**Issue by thejamescollins** [tectalic/simple-gallery#1]
As per W22743 & W25965.

Gallery shows a "Loading" graphic, and the main image never loads. Console shows:

```
Uncaught TypeError: e.browser is undefined
    a simple-gallery.js:67
    jQuery 2
simple-gallery.js:67
    a simple-gallery.js:67
```

Seems to be a compatibility issue with newer jQuery versions. [`$.browser` was removed from jQuery 1.9](https://jquery.com/upgrade-guide/1.9/#jquery-browser-removed).

**Comment by the-csaba** [comment]
Fixed via #2
